### ISSUE TITLE
Documentation does not specify what scope the environmental variable for the S3MaterialPoller needs.

### ISSUE THREAD

**Issue by joelp1** [indix/gocd-s3-artifacts#32]
Should the environmental variable be in the OS, or should it be within the GoCD Environment?

**Comment by ashwanthkumar** [comment]
Poller runs on the server - so you need to specify the environmental variables on the OS and restart the Go Server so that it picks it up. Only task plugins has information about the environment variables set in the pipeline and run with in an agent. 

Can you verify the same and if possible submit a PR for the update in documentation?

**Comment by ChrisKozak** [comment]
Is that a good design choice?  Is it possible for multiple teams, each with their own AWS sandbox, to use the plugin but with different credentials?

**Comment by ashwanthkumar** [comment]
> Is it possible for multiple teams, each with their own AWS sandbox, to use the plugin but with different credentials?

No, today it's not possible for material poller plugin. But you can do it for the publish and fetch plugins though. 

@ChrisKozak Actually it's a design choice of GoCD and not of the plugin. So far, we didn't have any issues with the approach. Can you please start a discussion on the mailing list of this concern? Someone should be able to help you create a patch for GoCD for this issue.

**Comment by ashwanthkumar** [comment]
@ChrisKozak I take back my word. There's a workaround actually. As part of the package configuration, would specifying the AWS profile work? You should then be able to specify multiple AWS Keys in `~/.aws/credentials` file. 

Thanks to awesome @manojlds for the idea.

**Comment by ChrisKozak** [comment]
We'll look into it, thanks!

**Comment by ashwanthkumar** [comment]
@ChrisKozak We still don't have an ability to specify the aws profile in the package configuration. If that approach sounds fine, we can either make that change or help you create a PR for the same.
