### ISSUE TITLE
Bad links on www.go.cd

### ISSUE THREAD

**Issue by ketan** [indix/gocd-s3-artifacts#42]
Hi,

I noticed that you moved your repositories and there's a bunch of bad links over at www.go.cd/plugins. I could not find all the replacement URLs, so I've pointed some of the links over to this repository instead of the GH pages site that you were using.

The relevant PR is [here](https://github.com/gocd/www.go.cd/pull/348) in case you'd like to tweak some of the links.

**Comment by manojlds** [comment]
Thanks @ketan . I will send a PR with fixes.

**Comment by manojlds** [comment]
Final PR - https://github.com/gocd/www.go.cd/pull/350

Closing this.
