### ISSUE TITLE
Plugins are not working with GoCD 17.2

### ISSUE THREAD

**Issue by algra** [indix/gocd-s3-artifacts#50]
Hi guys, it seems plug-ins API or so was changed within latest release of GoCD https://www.gocd.io/releases/#latest

```
Below is the list of plugins that will stop working in 17.2.0

Task plugins

...
Publish to S3
Fetch from S3
...
```

Any ideas if plugins will be updated to work with latest version of GoCD?

**Comment by algra** [comment]
Are pull requests with JSON API in titles are intended to solve this problem?

**Comment by manojlds** [comment]
Yes, we will be prioritizing that effort soon.

**Comment by mschmidtas24** [comment]
Hi guys, you have any updates for us? we using now 17.3.0 and still got problems

**Comment by manojlds** [comment]
Updated to JSON API, and tested against latest version (17.2.0+)
