### ISSUE TITLE
Use fetch artifact without using the material poller

### ISSUE THREAD

**Issue by rfhayashi** [indix/gocd-s3-artifacts#57]
I'd like to be able use this plugin the way I manage artifacts in GoCD. Say I have pipeline A which is material of pipeline B. If one of the steps of A publishes an artifact, I just need to add a task in pipeline B that fetches the artifact, and GoCD will figure out the correct artifact. Is this possible as of now? If I understood correctly I need to add the material poller to pipeline B instead of just adding A as a material of B.

I see that this plugin was created to manage artifacts across different servers, but it would be useful to use it inside the same server. My use case is that I need to manage the durability of the artifacts as GoCd saves them in disk, so saving in S3 would be a more trustable way of doing that.

**Comment by brewkode** [comment]
@rfhayashi Taking a stab at this. If I understand your need, you want a more reliable way of storing the artifacts that GoCD manages. Ideally, it should be the concern of Storage abstraction. i.e., we should be able to implement the storage backend and get done with it. That way, you can still continue to configure your pipeline dependencies as it is today and things would *just* work. 

> Say I have pipeline A which is material of pipeline B. If one of the steps of A publishes an artifact, I just need to add a task in pipeline B that fetches the artifact, and GoCD will figure out the correct artifact. Is this possible as of now?

You need to add the package as a material in pipeline B, similar to how you would add pipeline A as a dependency in B. Now, to the poller part. Behind the scenes, your GoCD server does in fact, poll the configured materials to look for "updates" to the configured set of materials. This is true for the existing pipeline based dependency world. For us to achieve this with the S3 backend, we need the same behavior, to know what is the latest of that material. This is why we need the s3 material poller too. Hope this helps.

**Comment by manojlds** [comment]
> I see that this plugin was created to manage artifacts across different servers, but it would be useful to use it inside the same server.

To address this point - while the main use case for us is that we can share artifacts across servers, the plugins can still be used within a single GoCD server.

> If I understood correctly I need to add the material poller to pipeline B instead of just adding A as a material of B.

@brewkode already touched upon this, but what do you consider as the difference between adding material poller pointing at A's S3 artifacts in B and adding A as a material of B?

**Comment by rfhayashi** [comment]
@brewkode and @manojlds, thank you for taking the time to answer.

@manojlds, I haven't yet tested the plugin, so forgive me if I'm wrong, but the difference is that I'd lose the value stream map as the dependency between the pipelines would be indirect.

**Comment by manojlds** [comment]
@rfhayashi - ah ok, got it. gocd-s3-artifacts uses the plugin extension points that GoCD offers, and this is the best we can do with that. We have the trackback url, but VSM is not possible.

**Comment by rfhayashi** [comment]
@manojlds Can you get the environment variables in a task? Then you could set the fetch task (or have another kind of task) with the name of the other pipeline material plus job name and name of the artifact. From the environment variables you could get "GO_DEPENDENCY_LOCATOR_<material>" which has as value "<pipeline>/<pipeline-counter>/<stage>/<stage-counter>". With that you could locate the file in s3. Does that make sense?

**Comment by manojlds** [comment]
@rfhayashi On some analysis, looks like we can try something out. Let me know if a functionality like this works for you:

1) Pipeline A publishes artifacts using the publish plugin.
2) Pipeline B is configured with Pipeline A as material (default gocd mechanism, not s3 poller)
3) Pipeline B uses fetch plugin to get artifacts.

**Comment by rfhayashi** [comment]
@manojlds That's exactly what I am looking for :) When you think you guys could work on this? I haven't yet developed a plugin, but I could try to make a PR if you're too busy right now.

**Comment by rfhayashi** [comment]
@manojlds To test the idea I've made a copy of the fetch plugin and changed it to do what we discussed. It worked very well for me. You can have a look at the code here: https://github.com/indix/gocd-s3-artifacts/compare/master...rfhayashi:fetch_artifact. I haven't opened a PR yet because I don't know if that would be the final implementation. We should probably continue to have just one plugin that does the two things, on the other hand I'm afraid it might confuse existent users. I'd love to hear if you have any ideas on that.

**Comment by manojlds** [comment]
@rfhayashi - this looks very like what I had in mind, but would have to be the same plugin with option to choose between poller or standard gocd artifacts locators.

**Comment by rfhayashi** [comment]
@manojlds Cool! I'll work on that. Do you know of any plugin that I can get an example of something like that? I'm thinking of having a combo box where you choose between poller and standard, and when the user selects that, the other appropriate fields for each case are shown. I'm not very familiar with angular, so having an example would help me a lot. Or you could give some direction if you know how to do this.

**Comment by manojlds** [comment]
@rfhayashi - https://github.com/manojlds/gocd-docker/blob/master/docker-task/src/main/resources/views/task.template.html#L9

Also, I can work on this over the weekend if it is too much trouble for you :)

**Comment by rfhayashi** [comment]
@manojlds Thank you so much! That's very kind of you, but I'd love to finish this up. Learning a lot in the process. One other thing that you could help me is about workflow. Whenever I need to test a change, I rebuild the plugin, copy to Go plugins folder, and restart Go. This takes a lot of time. The unit tests help a lot, but specially for GUI things you need to test in Go. Is there a better workflow?

**Comment by manojlds** [comment]
@rfhayashi I add `-DpluginLocationMonitor.sleepTimeInSecs=30` to server properties to reload plugins without restart.

**Comment by manojlds** [comment]
Available in https://github.com/indix/gocd-s3-artifacts/releases/tag/v4.0.0
