### ISSUE TITLE
Upgrade to Go json api

### ISSUE THREAD

**Issue by manojlds** [indix/gocd-s3-artifacts#6]

**Comment by ashwanthkumar** [comment]
GoCD from 17.x will stop supporting Java based Plugin API which is what we're using for Publish plugin. 

Ref - https://github.com/gocd/gocd/releases/tag/16.7.0

**Comment by ganeshpraburavi** [comment]
@manojlds Can you please provide some more details on what needs to be done?

**Comment by manojlds** [comment]
@ganeshpraburavi - https://developer.go.cd/16.4.0/writing_go_plugins/json_message_based_plugin_api.html

> Java interface based plugin API's makes it difficult to support backward compatibility for plugins, any change in the contract would mean plugins using older contract no longer work. Although multiple versions of API interfaces and classes can be maintained but it gets messy after sometime. JSON message based plugin API will help address this issue. Instead of implementing set of java interfaces to write a plugin, plugin authors have to implement a very thin java interface and rest of the communication between plugin and Go will be through JSON messages.

We are on the old API, and need to move to the newer one.

**Comment by ashwanthkumar** [comment]
If we're updating Publish plugin, check out - https://github.com/jmnarloch/gocd-task-plugin-api
