### ISSUE TITLE
Getting error using s3 material that region is not specified

### ISSUE THREAD

**Issue by dhaupertcognizant** [indix/gocd-s3-artifacts#63]
When trying to fetch a material I am seeing this error:
Interaction with plugin with id 's3material' implementing 'package-repository' extension failed while requesting for 'latest-revision'. Reason: [Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.]

Looking on google it seems that the initialization of AmazonS3Client should be done like this now:
AmazonS3 client = AmazonS3Client.builder().withRegion("us-east-1").withPathStyleAccessEnabled(true).build();

Has anyone seen this error or found a solution?

**Comment by manojlds** [comment]
Is the `AWS_REGION` set as mentioned in the docs?

http://oss.indix.com/gocd-s3-artifacts/installation.html

**Comment by dhaupertcognizant** [comment]
Thanks for responding.  Yes, indeed, we are setting the AWS_REGION in the environment variables set within the environment itself.  Anything else we can do to fix?

**Comment by manojlds** [comment]
Hey, is this on the server jvm process you mean? Or  environment variables within GoCD?

**Comment by dhaupertcognizant** [comment]
In the environment variables within GoCD.  If I click on Environments on GoCD Server, and then the settings cog/wheel it will be set/shown along the right side.

**Comment by manojlds** [comment]
That doesn't work for the material fetch since that happens in the server and not the agents. You need to set it in your shell environment / os / startup script etc.
