### ISSUE TITLE
Make Publish and Fetch task use the same client credentials as Material

### ISSUE THREAD

**Issue by manojlds** [indix/gocd-s3-artifacts#7]
The Material plugin picks up credentials as specified here - http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#AmazonS3Client()

The Publish and Fetch tasks pick the credentials only from the environment variables.

**Comment by mpgerlek** [comment]
+1

It would be simpler if the env vars for the key could be set in the s3material package repository dialog (or set it on a per-pipeline basis and use those env vars, like for pub and fetch).

**Comment by manojlds** [comment]
Fixed in #53
